name: bluetooth_test_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_blue_plus: 1.5.2 # only works for LE(Bluetooth Low Energy) devices
  flutter_easyloading: 3.0.5
  flutter_bluetooth_serial: 0.4.0 # not implemented yet
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

